# Generated by Django 4.1.2 on 2022-10-29 22:21

import branch_services.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatLicense',
            fields=[
                ('license_number', models.CharField(default=branch_services.models.get_new_license_number, max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('costume_name', models.CharField(max_length=32)),
                ('favorite_number', models.IntegerField()),
                ('photo', models.ImageField(default='treat_license_photos/default/top_view.jpg', upload_to=branch_services.models.get_id_photo_path)),
                ('issued_date', models.DateField(default=datetime.date.today)),
                ('expiration_date', models.DateField(default=datetime.date(2023, 10, 29))),
                ('treat_class', models.CharField(choices=[('ID', 'ID Card Only'), ('MM', 'M&Ms'), ('RS', 'Reeses'), ('SK', 'Skittles'), ('SN', 'Snickers'), ('SP', 'Sour Punch Straws'), ('TW', 'Twix')], default='ID', max_length=2)),
                ('treat_weight_oz', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('treat_length_in', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('issuer_code', models.CharField(max_length=5)),
            ],
        ),
    ]
