# Generated by Django 4.1.2 on 2022-10-25 06:42

import branch_services.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(default=branch_services.models.get_new_license_number, max_length=8)),
                ('first_name', models.CharField(max_length=32)),
                ('costume_name', models.CharField(max_length=32)),
                ('photo', models.FileField(upload_to=branch_services.models.get_treat_license_photo_path)),
                ('issued_date', models.DateField(default=datetime.date.today)),
                ('expiration_date', models.DateField(default=branch_services.models.get_new_license_expiration_date)),
                ('treat_class', models.CharField(choices=[('ID', 'ID Card Only'), ('MM', 'M&Ms'), ('RS', 'Reeses'), ('SK', 'Skittles'), ('SN', 'Snickers'), ('SP', 'Sour Punch Straws'), ('TW', 'Twix')], default='ID', max_length=2)),
                ('treat_weight_oz', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('treat_length_in', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
