# Generated by Django 4.1.2 on 2022-10-26 07:33

import branch_services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatlicense',
            name='id',
        ),
        migrations.AlterField(
            model_name='treatlicense',
            name='license_number',
            field=models.CharField(default=branch_services.models.get_new_license_number, max_length=8, primary_key=True, serialize=False),
        ),
    ]
