# Generated by Django 4.1.2 on 2022-10-26 08:06

import branch_services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_services', '0002_remove_treatlicense_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatlicense',
            name='photo',
            field=models.FileField(default='treat_license_photos/default/top_view.jpg', upload_to=branch_services.models.get_treat_license_photo_path),
        ),
    ]
